# Generated by Django 5.1.5 on 2025-02-04 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Product',
        ),
    ]
